# Hacky secret project 3

trigger:
- main

pr:
- main

jobs:
- job: Build
  strategy:
    matrix:
      mac:
        imageName: 'macos-10.15'
        isMac: True
      win:
        imageName: 'windows-2019'
        isWindows: True
      lin:
        imageName: 'ubuntu-20.04'
        isLinux: True

  pool:
    vmImage: $(imageName)

  steps:
  - checkout: self
    fetchDepth: 1
    # submodules: recursive # can't do submodules here b'cuz depth=1 fails with Github

  - bash: |
      cmake -Bbuild -DBUILD_STANDALONE_FS_TESTS=TRUE
    displayName: Run CMake

  - bash: |
      cmake --build build --config Release --target filesystem-tests
    displayName: Build filesystem test

  - bash: |
      ./build/products/filesystem-tests
    displayName: Run Tests

